export const OPTIONS = [
  [{ title: "Bus" }, { title: "Train" }],
  [{ title: "Banana" }, { title: "Strawberry" }],
  [{ title: "Cats" }, { title: "Dogs" }],
  [{ title: "City" }, { title: "Nature" }],
  [{ title: "Meat" }, { title: "Dairy" }],
  [{ title: "Blond" }, { title: "Brunette" }],
  [{ title: "Capitalism" }, { title: "Socialism" }],
  [{ title: "Black" }, { title: "White" }],
  [{ title: "Winter" }, { title: "Summer" }],
  [{ title: "Hot" }, { title: "Cold" }],
  [{ title: "Coffee" }, { title: "Tea" }],
  [{ title: "Blue" }, { title: "Red" }],
  [{ title: "Sleep" }, { title: "Wake Up" }],
  [{ title: "Soccer" }, { title: "Baskeball" }],
  [{ title: "Running" }, { title: "Swimming" }],
  [{ title: "Chocolate" }, { title: "Ice Cream" }],
  [{ title: "Breakfast" }, { title: "Lunch" }],
  [{ title: "Breakfast" }, { title: "Dinner" }],
  [{ title: "Lunch" }, { title: "Dinner" }],
  [{ title: "AM" }, { title: "PM" }],
  [{ title: "Batman" }, { title: "Superman" }],
  [{ title: "Stand Up" }, { title: "Sit Down" }],
  [{ title: "Wisdom" }, { title: "Beauty" }],
  [{ title: "California" }, { title: "New York" }],
  [{ title: "Money" }, { title: "Love" }],
  [{ title: "80's" }, { title: "90's" }],
  [{ title: "Pop Music" }, { title: "Rock" }],
  [{ title: "Rap Music" }, { title: "Rock" }],
  [{ title: "Rap" }, { title: "Pop Music" }],
  [{ title: "Elvis Presley" }, { title: "Michael Jackson" }],
  [{ title: "Friends" }, { title: "Seinfeld" }],
  [{ title: "TV" }, { title: "Cinema" }],
];
